version: 2

updates:
  # # https://github.com/dependabot/dependabot-core/issues/16026
  # - package-ecosystem: npm
  #   directory: /
  #   schedule:
  #     interval: weekly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
