name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Typecheck
        run: bun run typecheck

      - name: Test
        run: bun run test
        env:
          NUXT_SESSION_PASSWORD: 01234567890123456789012345678901
          NUXT_DATABASE_URL: file:./data/test.db
          NUXT_PUBLIC_SHORT_DOMAIN: http://localhost:3000
